# Generated by Django 3.1.4 on 2020-12-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addriver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='RiverRating',
            field=models.CharField(max_length=25),
        ),
    ]
